### ISSUE TITLE
프로젝트 설정 파일 (.yaml) 수정 필요

### ISSUE THREAD

**Issue by GunHee5719** [TEAMOTTDEVELOPERS/cocoman_server#19]
### Subject

application.yaml 파일 수정 필요

### Detail

현재 프로그램 작동을 위해 application-local.yaml 파일을 application.yaml 에 복사해서 붙여놨습니다.
추후 yaml 파일들 정리가 필요합니다!

**Comment by hihiboss** [comment]
#54로 새롭게 등록함
