### ISSUE TITLE
API Interface 작성

### ISSUE THREAD

**Issue by celi1004** [TEAMOTTDEVELOPERS/cocoman_server#26]
### Subject
API Interface 작성

### Detail

https://daddyprogrammer.org/post/404/spring-boot2-design-api-interface-and-data-structure/
혹시 위 게시물처럼 API 인터페이스 작성을 해야할까요??

**Comment by hihiboss** [comment]
Swagger와 Spring Rest Docs를 통해서 API 문서화가 가능하기 때문에 벼롣의 API 인터페이스 작성은 필요없을 것 같네요~
