### ISSUE TITLE
application.yaml 정리하기

### ISSUE THREAD

**Issue by hihiboss** [TEAMOTTDEVELOPERS/cocoman_server#54]
### Subject

각 환경별로 application.yaml 정리하기

### Detail

related: #3, #19

- application.yaml을 삭제하기
- application-dev.yaml 작성하기

추가로 application-dev.yaml에 DB 유저네임이나 비밀번호는 환경변수로 숨겨주세요. 그리고 EC2에 해당 환경 변수 세팅해주세요!

**Comment by GunHee5719** [comment]
Yes~~~
